--- 
- name: Configurar servidor de appp Java
  hosts: app01

  user: vagrant
  become: yes

  vars:
    - dbhost: "db01"
    - dbname: "notes"
    - dbusername: "notesapps"
    - dbpassword: "devopsmaonamassa"
  tasks:
    - name: Configurar hosts lab ansible
      lineinfile: 
          dest: /etc/hosts
          state: present
          line: "{{item}}"
      with_items:
        - 192.168.1.2 control-node
        - 192.168.1.3 app01
        - 192.168.1.4 db01