# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian/bullseye64"
  config.vm.hostname = "app01"
  config.vm.network "private_network", ip: "192.168.1.3"
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.provision "shell", path: "provision.sh"
  config.vm.provision :ansible do |ansible|
    ansible.playbook = "playbook.yml"
  end
end